name: LMBTFY Production CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Build
      run: dotnet build --configuration Release Lmbtfy.Web/Lmbtfy.Web.csproj

  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: 'Publish'
      run: dotnet publish -c Release -o ./lmbtfy-artifact Lmbtfy.Web/Lmbtfy.Web.csproj
    - name: 'Deploy'
      uses: azure/webapps-deploy@v1
      with:
        app-name: letmebingthatforyou
        publish-profile: ${{ secrets.LMBTFY_PUBLISH_PROFILE }}
        package: ./lmbtfy-artifact
